[theme]
base="light"
primaryColor="#d32f2f"            # red
backgroundColor="#ffffff"          # white
secondaryBackgroundColor="#f5f5f5" # light gray
textColor="#111111"                # near black
font="sans serif"